name: build

on: [pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # - name: Shellcheck
      #   uses: reviewdog/action-shellcheck@v1
      #   with:
      #     reporter: github-pr-review
      #     path: '.'
      #     pattern: '*.sh'
      #     exclude: './.git/*'

      # - name: Validate Cloud-Config
      #   run: |
      #     sudo apt-get update -y
      #     sudo apt-get install -y cloud-init
      #     cloud-init devel schema --config-file ./setup/cloud-config.yml

      # - name: Lint Ansible
      #   uses: ansible/ansible-lint@main
      #   env:
      #     ANSIBLE_CONFIG: ansible/ansible.cfg
      #   with:
      #     requirements_file: './ansible/requirements.yml'
      #     setup_python: 'true'
      #     working_directory: './ansible/playbooks'
